name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "rithikj2300@gmail.com"
          git config --global user.name "Keerthick2309"

          git clone https://huggingface.co/spaces/Keerthick/smartvision-ai hf_space

          rsync -av --exclude='.git' --exclude='smartvision_dataset' --exclude='CNNs_YOLO' ./ hf_space/

          cd hf_space
          git add .

          git diff --cached --quiet || git commit -m "Auto sync from GitHub"

          git push https://hf_user:$HF_TOKEN@huggingface.co/spaces/Keerthick/smartvision-ai main